"""
MySQL output module for changes_worker.

Uses aiomysql for async connection pooling and executes SQL statements
generated by the SchemaMapper based on mapping definitions.

MySQL-specific SQL:
  - Upsert uses INSERT ... ON DUPLICATE KEY UPDATE
  - Bind placeholders use %s style
  - Identifiers are back-tick quoted (`col`)
"""

import asyncio
import logging

try:
    from icecream import ic
except ImportError:
    ic = lambda *a, **kw: None  # noqa: E731

from db.db_base import BaseOutputForwarder, group_insert_ops, _MultiRowInsert
from pipeline.pipeline_logging import log_event

logger = logging.getLogger("changes_worker")

# Lazy import aiomysql
try:
    import aiomysql
except ImportError:
    aiomysql = None

# -- MySQL error classification --------------------------------------------------
# MySQL error codes that are transient (worth retrying).
_TRANSIENT_MYSQL_CODES = frozenset(
    {
        # Resource exhaustion
        1021,  # ER_DISK_FULL
        1037,  # ER_OUTOFMEMORY
        1038,  # ER_OUT_OF_SORTMEMORY
        1040,  # ER_CON_COUNT_ERROR (too many connections)
        1041,  # ER_OUT_OF_RESOURCES
        1114,  # ER_RECORD_FILE_FULL (table is full)
        # Server lifecycle
        1053,  # ER_SERVER_SHUTDOWN
        # Schema (may be recreated)
        1146,  # ER_NO_SUCH_TABLE — table may be recreated
        # Network
        1158,  # ER_NET_READ_ERROR
        1159,  # ER_NET_READ_INTERRUPTED
        1160,  # ER_NET_ERROR_ON_WRITE
        1161,  # ER_NET_WRITE_INTERRUPTED
        # Lock / deadlock
        1205,  # ER_LOCK_WAIT_TIMEOUT
        1206,  # ER_LOCK_TABLE_FULL (lock table exhausted)
        1213,  # ER_LOCK_DEADLOCK
        # Connection (client-side)
        2002,  # CR_CONNECTION_ERROR
        2003,  # CR_CONN_HOST_ERROR
        2006,  # CR_SERVER_GONE_ERROR
        2013,  # CR_SERVER_LOST
        2055,  # CR_SERVER_LOST_EXTENDED
    }
)


class MySQLOutputForwarder(BaseOutputForwarder):
    """
    Async MySQL output forwarder.

    Receives JSON documents from the changes feed, maps them to SQL
    operations via SchemaMapper, and executes against MySQL.
    """

    @property
    def _engine(self) -> str:
        return "mysql"

    def _get_engine_cfg(self, out_cfg: dict) -> dict:
        return out_cfg.get("db", None) or out_cfg.get("mysql", {})

    def __init__(self, out_cfg: dict, dry_run: bool = False, metrics=None):
        if aiomysql is None:
            raise RuntimeError("aiomysql library not installed – pip install aiomysql")

        super().__init__(out_cfg, dry_run, metrics=metrics)

        my_cfg = self._get_engine_cfg(out_cfg)
        self._host = my_cfg.get("host", "localhost")
        self._port = my_cfg.get("port", 3306)
        self._database = my_cfg.get("database", "")
        self._user = my_cfg.get("username", my_cfg.get("user", "root"))
        self._password = my_cfg.get("password", "")
        self._charset = my_cfg.get("charset", "utf8mb4")
        self._pool_min = my_cfg.get("pool_min", 2)
        self._pool_max = my_cfg.get("pool_max", 10)
        self._ssl = my_cfg.get("ssl", False)
        self._sync_commit = my_cfg.get("sync_commit", False)
        self._prepared_statements = my_cfg.get("prepared_statements", True)

        self._pool: "aiomysql.Pool | None" = None
        self._pool_lock = asyncio.Lock()

        self._init_metrics()

    # ── Pool lifecycle ──────────────────────────────────────────────────

    async def _connect_pool(self) -> None:
        ssl_ctx = None
        if self._ssl:
            import ssl as _ssl

            ssl_ctx = _ssl.create_default_context()
            ssl_ctx.check_hostname = False
            ssl_ctx.verify_mode = _ssl.CERT_NONE

        ic("_connect_pool", self._host, self._port, self._database)
        self._pool = await aiomysql.create_pool(
            host=self._host,
            port=self._port,
            db=self._database,
            user=self._user,
            password=self._password,
            charset=self._charset,
            minsize=self._pool_min,
            maxsize=self._pool_max,
            ssl=ssl_ctx,
            autocommit=False,
        )
        log_event(
            logger,
            "info",
            "OUTPUT",
            "MySQL pool created",
            host=self._host,
            port=self._port,
            db_name=self._database,
        )

    async def _close_pool(self) -> None:
        ic("_close_pool")
        pool, self._pool = self._pool, None
        if pool:
            pool.close()
            await pool.wait_closed()
            log_event(logger, "info", "OUTPUT", "MySQL pool closed")

    # ── MySQL SQL generation helpers ────────────────────────────────────

    @staticmethod
    def _op_to_mysql_sql(op) -> tuple[str, list]:
        """
        Convert a SqlOperation to MySQL-flavored SQL with %s placeholders.

        - DELETE  → DELETE FROM `table` WHERE `col` = %s
        - INSERT  → INSERT INTO `table` (`c1`,`c2`) VALUES (%s,%s)
        - UPSERT  → INSERT INTO ... ON DUPLICATE KEY UPDATE ...
        """
        if op.op_type == "DELETE":
            where = op.where or {}
            cols = list(where.keys())
            vals = [where[c] for c in cols]
            clauses = " AND ".join(f"`{c}` = %s" for c in cols)
            sql = f"DELETE FROM `{op.table}` WHERE {clauses}"
            return sql, vals

        if op.op_type == "INSERT":
            data = op.data or {}
            cols = list(data.keys())
            vals = [data[c] for c in cols]
            col_list = ", ".join(f"`{c}`" for c in cols)
            val_list = ", ".join("%s" for _ in cols)
            sql = f"INSERT INTO `{op.table}` ({col_list}) VALUES ({val_list})"
            return sql, vals

        if op.op_type == "UPSERT":
            data = op.data or {}
            cols = list(data.keys())
            vals = [data[c] for c in cols]
            pk = op.conflict_column or cols[0]

            col_list = ", ".join(f"`{c}`" for c in cols)
            val_list = ", ".join("%s" for _ in cols)
            update_set = ", ".join(f"`{c}` = VALUES(`{c}`)" for c in cols if c != pk)

            sql = f"INSERT INTO `{op.table}` ({col_list}) VALUES ({val_list})"
            if update_set:
                sql += f" ON DUPLICATE KEY UPDATE {update_set}"
            return sql, vals

        raise ValueError(f"Unknown op_type: {op.op_type!r}")

    # ── SQL execution ───────────────────────────────────────────────────

    @staticmethod
    def _multi_row_insert_sql(mri: _MultiRowInsert) -> tuple[str, list]:
        """Build a single INSERT … VALUES (…),(…),… for MySQL %s placeholders."""
        col_list = ", ".join(f"`{c}`" for c in mri.columns)
        row_ph = "(%s)" % ", ".join("%s" for _ in mri.columns)
        values_clause = ", ".join(row_ph for _ in mri.rows)
        params: list = []
        for row in mri.rows:
            params.extend(row)
        sql = f"INSERT INTO `{mri.table}` ({col_list}) VALUES {values_clause}"
        return sql, params

    async def _execute_ops(self, ops: list) -> None:
        pool = self._pool
        if pool is None:
            raise ConnectionError("MySQL pool is not connected")
        grouped = group_insert_ops(ops)
        ic("_execute_ops", len(ops), "grouped", len(grouped))
        async with pool.acquire() as conn:
            try:
                async with conn.cursor() as cur:
                    if not self._sync_commit:
                        await cur.execute("SET innodb_flush_log_at_trx_commit = 2")
                    for op in grouped:
                        if isinstance(op, _MultiRowInsert):
                            sql, params = self._multi_row_insert_sql(op)
                            log_event(
                                logger,
                                "debug",
                                "OUTPUT",
                                "SQL exec (multi-row INSERT, %d rows)" % len(op.rows),
                                operation="INSERT",
                            )
                            await cur.execute(sql, params)
                        else:
                            sql, params = self._op_to_mysql_sql(op)
                            log_event(
                                logger,
                                "debug",
                                "OUTPUT",
                                "SQL exec",
                                operation=op.op_type,
                            )
                            await cur.execute(sql, params)
                await conn.commit()
            except Exception:
                await conn.rollback()
                raise

    # ── Error classification ────────────────────────────────────────────

    def _is_transient(self, exc: Exception) -> bool:
        if aiomysql is None:
            return False
        if isinstance(exc, (ConnectionError, OSError, TimeoutError)):
            return True
        if isinstance(exc, aiomysql.Error):
            code = getattr(exc, "args", (None,))[0]
            if isinstance(code, int):
                return code in _TRANSIENT_MYSQL_CODES
        return False

    def _error_class(self, exc: Exception) -> str:
        if aiomysql is None:
            return "unknown"
        if isinstance(exc, TimeoutError):
            return "timeout"
        if isinstance(exc, (ConnectionError, OSError)):
            return "connection"
        if isinstance(exc, aiomysql.Error):
            code = getattr(exc, "args", (None,))[0]
            if isinstance(code, int):
                # Connection
                if code in (2002, 2003, 2006, 2013, 2055):
                    return "connection"
                # Network
                if code in (1158, 1159, 1160, 1161):
                    return "connection"
                # Lock / deadlock
                if code in (1205, 1213):
                    return "deadlock"
                if code == 1206:
                    return "lock_contention"
                # Resource exhaustion
                if code in (1021, 1037, 1038, 1040, 1041, 1114):
                    return "resource_exhaustion"
                # Server lifecycle
                if code == 1053:
                    return "server_shutdown"
                # Constraint violations
                if code in (1062, 1557):
                    return "constraint_violation"
                if code in (1451, 1452, 1216, 1217):
                    return "constraint_violation"
                if code in (1048, 1364):
                    return "constraint_violation"
                if code == 3819:
                    return "constraint_violation"
                # Data type errors
                if code in (1264, 1265, 1366, 1292, 1406, 1411):
                    return "data_type"
                # Schema (table may be recreated)
                if code == 1146:
                    return "table_not_found"
                # Syntax / schema (permanent)
                if code in (1054, 1064, 1136):
                    return "syntax_or_schema"
                # Auth / permission (permanent)
                if code in (1044, 1045, 1142):
                    return "auth_failure"
                # Database config (permanent)
                if code in (1046, 1049):
                    return "invalid_database"
                if code == 1290:
                    return "read_only"
                return f"mysql_{code}"
        return "unknown"

    # ── Health check ────────────────────────────────────────────────────

    async def _test_connection(self) -> None:
        pool = self._pool
        if pool is None:
            raise ConnectionError("MySQL pool is not connected")
        async with pool.acquire() as conn:
            async with conn.cursor() as cur:
                await cur.execute("SELECT 1")
        ic("_test_connection: OK", self._host, self._port, self._database)
        log_event(
            logger,
            "info",
            "OUTPUT",
            "MySQL reachable",
            host=self._host,
            port=self._port,
            db_name=self._database,
        )


# ── Introspection (standalone functions, not part of the forwarder) ──────


async def introspect_tables(my_cfg: dict) -> list[dict]:
    """
    Connect to MySQL and return all tables with their columns.

    Returns the same structure as db_postgres.introspect_tables.
    """
    if aiomysql is None:
        raise RuntimeError("aiomysql library not installed – pip install aiomysql")

    ssl_ctx = None
    if my_cfg.get("ssl"):
        import ssl as _ssl

        ssl_ctx = _ssl.create_default_context()
        ssl_ctx.check_hostname = False
        ssl_ctx.verify_mode = _ssl.CERT_NONE

    conn = await aiomysql.connect(
        host=my_cfg.get("host", "localhost"),
        port=my_cfg.get("port", 3306),
        db=my_cfg.get("database", ""),
        user=my_cfg.get("user", "root"),
        password=my_cfg.get("password", ""),
        charset=my_cfg.get("charset", "utf8mb4"),
        ssl=ssl_ctx,
    )

    try:
        database = my_cfg.get("database", "")
        cur = await conn.cursor()
        try:
            # Get all tables
            await cur.execute(
                "SELECT table_name FROM information_schema.tables "
                "WHERE table_schema = %s AND table_type = 'BASE TABLE' "
                "ORDER BY table_name",
                (database,),
            )
            table_rows = await cur.fetchall()

            result = []
            for (table_name,) in table_rows:
                # Get columns
                await cur.execute(
                    "SELECT column_name, data_type, column_type, is_nullable, "
                    "column_default, character_maximum_length, "
                    "numeric_precision, numeric_scale "
                    "FROM information_schema.columns "
                    "WHERE table_schema = %s AND table_name = %s "
                    "ORDER BY ordinal_position",
                    (database, table_name),
                )
                col_rows = await cur.fetchall()

                columns = []
                for (
                    col_name,
                    data_type,
                    column_type,
                    is_nullable,
                    default_val,
                    char_max_len,
                    num_prec,
                    num_scale,
                ) in col_rows:
                    columns.append(
                        {
                            "name": col_name,
                            "type": data_type,
                            "display_type": column_type,
                            "nullable": is_nullable == "YES",
                            "default": default_val,
                        }
                    )

                # Get primary key columns
                await cur.execute(
                    "SELECT column_name "
                    "FROM information_schema.key_column_usage "
                    "WHERE table_schema = %s AND table_name = %s "
                    "AND constraint_name = 'PRIMARY' "
                    "ORDER BY ordinal_position",
                    (database, table_name),
                )
                pk_rows = await cur.fetchall()
                pk_cols = [r[0] for r in pk_rows]

                # Get foreign keys
                await cur.execute(
                    "SELECT column_name, referenced_table_name, "
                    "referenced_column_name "
                    "FROM information_schema.key_column_usage "
                    "WHERE table_schema = %s AND table_name = %s "
                    "AND referenced_table_name IS NOT NULL",
                    (database, table_name),
                )
                fk_rows = await cur.fetchall()
                fks = [
                    {
                        "column": r[0],
                        "references_table": r[1],
                        "references_column": r[2],
                    }
                    for r in fk_rows
                ]

                result.append(
                    {
                        "table_name": table_name,
                        "schema": database,
                        "columns": columns,
                        "primary_key": pk_cols,
                        "foreign_keys": fks,
                    }
                )

            return result
        finally:
            await cur.close()
    finally:
        conn.close()


async def introspect_single_table(my_cfg: dict, table_name: str) -> dict | None:
    """Introspect a single table. Returns the table dict or None."""
    tables = await introspect_tables(my_cfg)
    for t in tables:
        if t["table_name"] == table_name:
            return t
    return None
