"""
Microsoft SQL Server output module for changes_worker.

Uses aioodbc for async connection pooling and executes SQL statements
generated by the SchemaMapper based on mapping definitions.

MSSQL-specific SQL:
  - Upsert uses MERGE ... WHEN MATCHED THEN UPDATE WHEN NOT MATCHED THEN INSERT
  - Bind placeholders use ? style
  - Identifiers are bracket-quoted ([col])
"""

import asyncio
import logging

from db.db_base import BaseOutputForwarder, group_insert_ops, _MultiRowInsert
from pipeline.pipeline_logging import log_event

try:
    from icecream import ic
except ImportError:
    ic = lambda *a, **kw: None  # noqa: E731

logger = logging.getLogger("changes_worker")

# Lazy import aioodbc
try:
    import aioodbc
except ImportError:
    aioodbc = None

# -- MSSQL error classification --------------------------------------------------
# SQL Server error numbers that are transient (worth retrying).
_TRANSIENT_MSSQL_CODES = frozenset(
    {
        -1,  # General network error / connection failure
        2,  # Timeout expired
        53,  # Named pipe provider: could not open connection
        233,  # Connection was forcibly closed
        258,  # Timeout waiting for login response
        1205,  # Deadlock victim
        10054,  # Connection reset by peer
        10060,  # Connection timed out
        10061,  # Connection refused
        40143,  # Connection could not be initialized
        40197,  # Service encountered an error processing your request
        40501,  # Service busy
        40613,  # Database is currently unavailable
        49918,  # Cannot process request: not enough resources
        49919,  # Cannot process create/update request
        49920,  # Cannot process request: too many operations in progress
    }
)


class MSSQLOutputForwarder(BaseOutputForwarder):
    """
    Async MS SQL Server output forwarder.

    Receives JSON documents from the changes feed, maps them to SQL
    operations via SchemaMapper, and executes against SQL Server.
    """

    @property
    def _engine(self) -> str:
        return "mssql"

    def _get_engine_cfg(self, out_cfg: dict) -> dict:
        return out_cfg.get("db", None) or out_cfg.get("mssql", {})

    def __init__(self, out_cfg: dict, dry_run: bool = False, metrics=None):
        if aioodbc is None:
            raise RuntimeError("aioodbc library not installed – pip install aioodbc")

        super().__init__(out_cfg, dry_run, metrics=metrics)

        ms_cfg = self._get_engine_cfg(out_cfg)
        self._host = ms_cfg.get("host", "localhost")
        self._port = ms_cfg.get("port", 1433)
        self._database = ms_cfg.get("database", "")
        self._user = ms_cfg.get("username", ms_cfg.get("user", "sa"))
        self._password = ms_cfg.get("password", "")
        self._schema = ms_cfg.get("schema", "dbo")
        self._driver = ms_cfg.get("odbc_driver", "ODBC Driver 18 for SQL Server")
        self._pool_min = ms_cfg.get("pool_min", 2)
        self._pool_max = ms_cfg.get("pool_max", 10)
        self._trust_cert = ms_cfg.get("trust_server_certificate", True)
        self._sync_commit = ms_cfg.get("sync_commit", False)
        self._prepared_statements = ms_cfg.get("prepared_statements", True)

        self._dsn = self._build_dsn()
        self._pool: "aioodbc.Pool | None" = None
        self._pool_lock = asyncio.Lock()

        self._init_metrics()

    def _build_dsn(self) -> str:
        parts = [
            f"DRIVER={{{self._driver}}}",
            f"SERVER={self._host},{self._port}",
            f"DATABASE={self._database}",
            f"UID={self._user}",
            f"PWD={self._password}",
        ]
        if self._trust_cert:
            parts.append("TrustServerCertificate=yes")
        return ";".join(parts)

    # ── Pool lifecycle ──────────────────────────────────────────────────

    async def _connect_pool(self) -> None:
        ic("_connect_pool", self._host, self._port, self._database)
        self._pool = await aioodbc.create_pool(
            dsn=self._dsn,
            minsize=self._pool_min,
            maxsize=self._pool_max,
        )
        log_event(
            logger,
            "info",
            "OUTPUT",
            "MSSQL pool created",
            host=self._host,
            port=self._port,
            db_name=self._database,
        )

    async def _close_pool(self) -> None:
        ic("_close_pool")
        pool, self._pool = self._pool, None
        if pool:
            pool.close()
            await pool.wait_closed()
            log_event(logger, "info", "OUTPUT", "MSSQL pool closed")

    async def _reconnect_pool(self) -> None:
        ic("_reconnect_pool")
        async with self._pool_lock:
            await self._close_pool()
            await self._connect_pool()

    # ── MSSQL SQL generation helpers ────────────────────────────────────

    @staticmethod
    def _op_to_mssql_sql(op) -> tuple[str, list]:
        """
        Convert a SqlOperation to MSSQL-flavored SQL with ? placeholders.

        - DELETE  → DELETE FROM [table] WHERE [col] = ?
        - INSERT  → INSERT INTO [table] ([c1],[c2]) VALUES (?,?)
        - UPSERT  → MERGE [table] AS t USING (VALUES (?,?)) AS s([c1],[c2])
                     ON t.[pk] = s.[pk]
                     WHEN MATCHED THEN UPDATE SET ...
                     WHEN NOT MATCHED THEN INSERT ...;
        """
        if op.op_type == "DELETE":
            where = op.where or {}
            cols = list(where.keys())
            vals = [where[c] for c in cols]
            clauses = " AND ".join(f"[{c}] = ?" for c in cols)
            sql = f"DELETE FROM [{op.table}] WHERE {clauses}"
            return sql, vals

        if op.op_type == "INSERT":
            data = op.data or {}
            cols = list(data.keys())
            vals = [data[c] for c in cols]
            col_list = ", ".join(f"[{c}]" for c in cols)
            val_list = ", ".join("?" for _ in cols)
            sql = f"INSERT INTO [{op.table}] ({col_list}) VALUES ({val_list})"
            return sql, vals

        if op.op_type == "UPSERT":
            data = op.data or {}
            cols = list(data.keys())
            vals = [data[c] for c in cols]
            pk = op.conflict_column or cols[0]

            col_list = ", ".join(f"[{c}]" for c in cols)
            val_list = ", ".join("?" for _ in cols)
            on_clause = f"t.[{pk}] = s.[{pk}]"
            update_set = ", ".join(f"t.[{c}] = s.[{c}]" for c in cols if c != pk)
            insert_cols = ", ".join(f"[{c}]" for c in cols)
            insert_vals = ", ".join(f"s.[{c}]" for c in cols)

            sql = (
                f"MERGE [{op.table}] AS t "
                f"USING (VALUES ({val_list})) AS s({col_list}) "
                f"ON ({on_clause}) "
            )
            if update_set:
                sql += f"WHEN MATCHED THEN UPDATE SET {update_set} "
            sql += (
                f"WHEN NOT MATCHED THEN INSERT ({insert_cols}) VALUES ({insert_vals});"
            )
            return sql, vals

        raise ValueError(f"Unknown op_type: {op.op_type!r}")

    # ── SQL execution ───────────────────────────────────────────────────

    @staticmethod
    def _multi_row_insert_sql(mri: _MultiRowInsert) -> tuple[str, list]:
        """Build a single INSERT … VALUES (…),(…),… for MSSQL ? placeholders."""
        col_list = ", ".join(f"[{c}]" for c in mri.columns)
        row_ph = "(%s)" % ", ".join("?" for _ in mri.columns)
        values_clause = ", ".join(row_ph for _ in mri.rows)
        params: list = []
        for row in mri.rows:
            params.extend(row)
        sql = f"INSERT INTO [{mri.table}] ({col_list}) VALUES {values_clause}"
        return sql, params

    async def _execute_ops(self, ops: list) -> None:
        pool = self._pool
        if pool is None:
            raise ConnectionError("MSSQL pool is not connected")
        grouped = group_insert_ops(ops)
        ic("_execute_ops", len(ops), "grouped", len(grouped))
        async with pool.acquire() as conn:
            try:
                async with conn.cursor() as cur:
                    if not self._sync_commit:
                        await cur.execute("SET DELAYED_DURABILITY = ON")
                    for op in grouped:
                        if isinstance(op, _MultiRowInsert):
                            sql, params = self._multi_row_insert_sql(op)
                            log_event(
                                logger,
                                "debug",
                                "OUTPUT",
                                "SQL exec (multi-row INSERT, %d rows)" % len(op.rows),
                                operation="INSERT",
                            )
                            await cur.execute(sql, *params)
                        else:
                            sql, params = self._op_to_mssql_sql(op)
                            log_event(
                                logger,
                                "debug",
                                "OUTPUT",
                                "SQL exec",
                                operation=op.op_type,
                            )
                            await cur.execute(sql, *params)
                await conn.commit()
            except Exception:
                await conn.rollback()
                raise

    # ── Error classification ────────────────────────────────────────────

    def _is_transient(self, exc: Exception) -> bool:
        if aioodbc is None:
            return False
        if isinstance(exc, (ConnectionError, OSError, TimeoutError)):
            return True
        code = _mssql_error_code(exc)
        if code is not None:
            return code in _TRANSIENT_MSSQL_CODES
        return False

    def _error_class(self, exc: Exception) -> str:
        if aioodbc is None:
            return "unknown"
        if isinstance(exc, TimeoutError):
            return "timeout"
        if isinstance(exc, (ConnectionError, OSError)):
            return "connection"
        code = _mssql_error_code(exc)
        if code is not None:
            if code in (-1, 53, 233, 10054, 10060, 10061, 40143, 40197, 40613):
                return "connection"
            if code in (2, 258):
                return "timeout"
            if code == 1205:
                return "deadlock"
            if code in (2601, 2627, 547, 515):
                return "constraint_violation"
            if code in (245, 8114, 8115):
                return "data_type"
            if code in (207, 208, 102):
                return "syntax_or_schema"
            return f"mssql_{code}"
        return "unknown"

    # ── Health check ────────────────────────────────────────────────────

    async def _test_connection(self) -> None:
        pool = self._pool
        if pool is None:
            raise ConnectionError("MSSQL pool is not connected")
        async with pool.acquire() as conn:
            async with conn.cursor() as cur:
                await cur.execute("SELECT 1")
        ic("_test_connection: OK", self._host, self._port, self._database)
        log_event(
            logger,
            "info",
            "OUTPUT",
            "MSSQL reachable",
            host=self._host,
            port=self._port,
            db_name=self._database,
        )


def _mssql_error_code(exc: Exception) -> int | None:
    """Extract the SQL Server error number from a pyodbc/aioodbc exception."""
    args = getattr(exc, "args", ())
    if args and isinstance(args[0], str):
        # pyodbc format: "('HYxxx', '[HYxxx] [Microsoft][ODBC ...] error (code) ...')"
        import re

        m = re.search(r"\((\d+)\)", args[0])
        if m:
            return int(m.group(1))
    if args and isinstance(args[0], int):
        return args[0]
    return None


# ── Introspection (standalone functions, not part of the forwarder) ──────


async def introspect_tables(ms_cfg: dict) -> list[dict]:
    """
    Connect to SQL Server and return all tables with their columns.

    Returns the same structure as db_postgres.introspect_tables.
    """
    if aioodbc is None:
        raise RuntimeError("aioodbc library not installed – pip install aioodbc")

    driver = ms_cfg.get("odbc_driver", "ODBC Driver 18 for SQL Server")
    host = ms_cfg.get("host", "localhost")
    port = ms_cfg.get("port", 1433)
    database = ms_cfg.get("database", "")
    user = ms_cfg.get("user", "sa")
    password = ms_cfg.get("password", "")
    trust_cert = ms_cfg.get("trust_server_certificate", True)
    schema = ms_cfg.get("schema", "dbo")

    dsn_parts = [
        f"DRIVER={{{driver}}}",
        f"SERVER={host},{port}",
        f"DATABASE={database}",
        f"UID={user}",
        f"PWD={password}",
    ]
    if trust_cert:
        dsn_parts.append("TrustServerCertificate=yes")
    dsn = ";".join(dsn_parts)

    conn = await aioodbc.connect(dsn=dsn)

    try:
        cur = await conn.cursor()
        try:
            # Get all tables
            await cur.execute(
                "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES "
                "WHERE TABLE_SCHEMA = ? AND TABLE_TYPE = 'BASE TABLE' "
                "ORDER BY TABLE_NAME",
                schema,
            )
            table_rows = await cur.fetchall()

            result = []
            for (table_name,) in table_rows:
                # Get columns
                await cur.execute(
                    "SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, "
                    "COLUMN_DEFAULT, CHARACTER_MAXIMUM_LENGTH, "
                    "NUMERIC_PRECISION, NUMERIC_SCALE "
                    "FROM INFORMATION_SCHEMA.COLUMNS "
                    "WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? "
                    "ORDER BY ORDINAL_POSITION",
                    schema,
                    table_name,
                )
                col_rows = await cur.fetchall()

                columns = []
                for (
                    col_name,
                    data_type,
                    is_nullable,
                    default_val,
                    char_max_len,
                    num_prec,
                    num_scale,
                ) in col_rows:
                    display_type = data_type
                    if char_max_len is not None:
                        if char_max_len == -1:
                            display_type += "(max)"
                        else:
                            display_type += f"({char_max_len})"
                    elif num_prec is not None and data_type in (
                        "numeric",
                        "decimal",
                    ):
                        display_type += f"({num_prec},{num_scale or 0})"

                    columns.append(
                        {
                            "name": col_name,
                            "type": data_type,
                            "display_type": display_type,
                            "nullable": is_nullable == "YES",
                            "default": default_val,
                        }
                    )

                # Get primary key columns
                await cur.execute(
                    "SELECT kcu.COLUMN_NAME "
                    "FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc "
                    "JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu "
                    "  ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME "
                    "  AND tc.TABLE_SCHEMA = kcu.TABLE_SCHEMA "
                    "WHERE tc.TABLE_SCHEMA = ? AND tc.TABLE_NAME = ? "
                    "  AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY' "
                    "ORDER BY kcu.ORDINAL_POSITION",
                    schema,
                    table_name,
                )
                pk_rows = await cur.fetchall()
                pk_cols = [r[0] for r in pk_rows]

                # Get foreign keys
                await cur.execute(
                    "SELECT ccu.COLUMN_NAME, "
                    "  kcu2.TABLE_NAME AS REFERENCES_TABLE, "
                    "  kcu2.COLUMN_NAME AS REFERENCES_COLUMN "
                    "FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc "
                    "JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE ccu "
                    "  ON rc.CONSTRAINT_NAME = ccu.CONSTRAINT_NAME "
                    "  AND rc.CONSTRAINT_SCHEMA = ccu.TABLE_SCHEMA "
                    "JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu2 "
                    "  ON rc.UNIQUE_CONSTRAINT_NAME = kcu2.CONSTRAINT_NAME "
                    "  AND rc.UNIQUE_CONSTRAINT_SCHEMA = kcu2.TABLE_SCHEMA "
                    "  AND ccu.ORDINAL_POSITION = kcu2.ORDINAL_POSITION "
                    "WHERE ccu.TABLE_SCHEMA = ? AND ccu.TABLE_NAME = ?",
                    schema,
                    table_name,
                )
                fk_rows = await cur.fetchall()
                fks = [
                    {
                        "column": r[0],
                        "references_table": r[1],
                        "references_column": r[2],
                    }
                    for r in fk_rows
                ]

                result.append(
                    {
                        "table_name": table_name,
                        "schema": schema,
                        "columns": columns,
                        "primary_key": pk_cols,
                        "foreign_keys": fks,
                    }
                )

            return result
        finally:
            await cur.close()
    finally:
        await conn.close()


async def introspect_single_table(ms_cfg: dict, table_name: str) -> dict | None:
    """Introspect a single table. Returns the table dict or None."""
    tables = await introspect_tables(ms_cfg)
    for t in tables:
        if t["table_name"] == table_name:
            return t
    return None
