"""
Oracle Database output module for changes_worker.

Uses oracledb (the official Oracle async driver, successor to cx_Oracle)
for async connection pooling and executes SQL statements generated by
the SchemaMapper based on mapping definitions.

Oracle-specific SQL:
  - Upsert uses MERGE INTO ... USING DUAL WHEN MATCHED / WHEN NOT MATCHED
  - Bind placeholders use :1, :2, ... style
  - Identifiers are double-quoted (same as PostgreSQL)
"""

import asyncio
import logging

from db.db_base import BaseOutputForwarder, group_insert_ops, _MultiRowInsert
from pipeline_logging import log_event

try:
    from icecream import ic
except ImportError:
    ic = lambda *a, **kw: None  # noqa: E731

logger = logging.getLogger("changes_worker")

# Lazy import oracledb
try:
    import oracledb
except ImportError:
    oracledb = None

# -- Oracle error classification ------------------------------------------------
# ORA error codes that are transient (worth retrying).
_TRANSIENT_ORA_CODES = frozenset(
    {
        3113,  # end-of-file on communication channel
        3114,  # not connected to ORACLE
        3135,  # connection lost contact
        12170,  # TNS:Connect timeout occurred
        12541,  # TNS:no listener
        12543,  # TNS:destination host unreachable
        25408,  # can not safely replay call
        60,  # deadlock detected while waiting for resource
    }
)


def _ora_error_code(exc: Exception) -> int | None:
    """Extract the ORA error code from an oracledb exception."""
    if oracledb is None:
        return None
    if isinstance(exc, oracledb.Error):
        args = exc.args
        if args and hasattr(args[0], "code"):
            return args[0].code
    return None


class OracleOutputForwarder(BaseOutputForwarder):
    """
    Async Oracle output forwarder.

    Receives JSON documents from the changes feed, maps them to SQL
    operations via SchemaMapper, and executes against Oracle Database.
    """

    @property
    def _engine(self) -> str:
        return "oracle"

    def _get_engine_cfg(self, out_cfg: dict) -> dict:
        return out_cfg.get("db", None) or out_cfg.get("oracle", {})

    def __init__(self, out_cfg: dict, dry_run: bool = False, metrics=None):
        if oracledb is None:
            raise RuntimeError("oracledb library not installed – pip install oracledb")

        super().__init__(out_cfg, dry_run, metrics=metrics)

        ora_cfg = self._get_engine_cfg(out_cfg)
        self._host = ora_cfg.get("host", "localhost")
        self._port = ora_cfg.get("port", 1521)
        self._database = ora_cfg.get("database", "")  # service name
        self._user = ora_cfg.get("username", ora_cfg.get("user", ""))
        self._password = ora_cfg.get("password", "")
        self._schema = ora_cfg.get("schema", "")
        self._pool_min = ora_cfg.get("pool_min", 2)
        self._pool_max = ora_cfg.get("pool_max", 10)
        self._sync_commit = ora_cfg.get("sync_commit", False)
        self._prepared_statements = ora_cfg.get("prepared_statements", True)

        # Build DSN
        self._dsn = ora_cfg.get("dsn", "")
        if not self._dsn:
            self._dsn = f"{self._host}:{self._port}/{self._database}"

        self._pool: "oracledb.AsyncConnectionPool | None" = None
        self._pool_lock = asyncio.Lock()

        self._init_metrics()

    # ── Pool lifecycle ──────────────────────────────────────────────────

    async def _connect_pool(self) -> None:
        ic("_connect_pool", self._dsn, self._pool_min, self._pool_max)
        self._pool = oracledb.create_pool_async(
            user=self._user,
            password=self._password,
            dsn=self._dsn,
            min=self._pool_min,
            max=self._pool_max,
        )
        log_event(
            logger,
            "info",
            "OUTPUT",
            "Oracle pool created",
            host=self._dsn,
            mode="db",
        )

    async def _close_pool(self) -> None:
        ic("_close_pool")
        pool, self._pool = self._pool, None
        if pool:
            await pool.close()
            log_event(logger, "info", "OUTPUT", "Oracle pool closed", mode="db")

    async def _reconnect_pool(self) -> None:
        ic("_reconnect_pool")
        async with self._pool_lock:
            await self._close_pool()
            await self._connect_pool()

    # ── Oracle SQL generation helpers ───────────────────────────────────

    @staticmethod
    def _op_to_oracle_sql(op) -> tuple[str, list]:
        """
        Convert a SqlOperation to Oracle-flavored SQL with :1, :2, ... binds.

        - DELETE  → DELETE FROM "table" WHERE "col" = :1
        - INSERT  → INSERT INTO "table" ("c1","c2") VALUES (:1,:2)
        - UPSERT  → MERGE INTO ... USING DUAL ...
        """
        if op.op_type == "DELETE":
            where = op.where or {}
            cols = list(where.keys())
            vals = [where[c] for c in cols]
            clauses = " AND ".join(f'"{c}" = :{i}' for i, c in enumerate(cols, 1))
            sql = f'DELETE FROM "{op.table}" WHERE {clauses}'
            return sql, vals

        if op.op_type == "INSERT":
            data = op.data or {}
            cols = list(data.keys())
            vals = [data[c] for c in cols]
            col_list = ", ".join(f'"{c}"' for c in cols)
            val_list = ", ".join(f":{i}" for i in range(1, len(cols) + 1))
            sql = f'INSERT INTO "{op.table}" ({col_list}) VALUES ({val_list})'
            return sql, vals

        if op.op_type == "UPSERT":
            data = op.data or {}
            cols = list(data.keys())
            vals = [data[c] for c in cols]
            pk = op.conflict_column or cols[0]

            # MERGE INTO "table" t
            # USING (SELECT :1 AS "pk", :2 AS "c2", ... FROM DUAL) s
            # ON (t."pk" = s."pk")
            # WHEN MATCHED THEN UPDATE SET t."c2" = s."c2", ...
            # WHEN NOT MATCHED THEN INSERT ("pk","c2",...) VALUES (s."pk",s."c2",...)
            select_cols = ", ".join(f':{i} AS "{c}"' for i, c in enumerate(cols, 1))
            on_clause = f't."{pk}" = s."{pk}"'
            update_set = ", ".join(f't."{c}" = s."{c}"' for c in cols if c != pk)
            insert_cols = ", ".join(f'"{c}"' for c in cols)
            insert_vals = ", ".join(f's."{c}"' for c in cols)

            sql = (
                f'MERGE INTO "{op.table}" t '
                f"USING (SELECT {select_cols} FROM DUAL) s "
                f"ON ({on_clause}) "
            )
            if update_set:
                sql += f"WHEN MATCHED THEN UPDATE SET {update_set} "
            sql += (
                f"WHEN NOT MATCHED THEN INSERT ({insert_cols}) VALUES ({insert_vals})"
            )
            return sql, vals

        raise ValueError(f"Unknown op_type: {op.op_type!r}")

    # ── SQL execution ───────────────────────────────────────────────────

    @staticmethod
    def _multi_row_insert_sql(mri: _MultiRowInsert) -> tuple[str, list]:
        """Build INSERT ALL … SELECT FROM DUAL for Oracle :N bind placeholders."""
        col_list = ", ".join(f'"{c}"' for c in mri.columns)
        parts: list[str] = []
        params: list = []
        idx = 1
        for row in mri.rows:
            val_list = ", ".join(f":{idx + i}" for i in range(len(row)))
            parts.append(f'INTO "{mri.table}" ({col_list}) VALUES ({val_list})')
            params.extend(row)
            idx += len(row)
        sql = "INSERT ALL " + " ".join(parts) + " SELECT 1 FROM DUAL"
        return sql, params

    async def _execute_ops(self, ops: list) -> None:
        pool = self._pool
        if pool is None:
            raise ConnectionError("Oracle pool is not connected")
        grouped = group_insert_ops(ops)
        ic("_execute_ops", len(ops), "grouped", len(grouped))
        async with pool.acquire() as conn:
            try:
                async with conn.cursor() as cur:
                    if not self._sync_commit:
                        await cur.execute(
                            "ALTER SESSION SET COMMIT_WRITE = 'BATCH, NOWAIT'"
                        )
                    for op in grouped:
                        if isinstance(op, _MultiRowInsert):
                            sql, params = self._multi_row_insert_sql(op)
                            log_event(
                                logger,
                                "debug",
                                "OUTPUT",
                                "SQL exec (multi-row INSERT, %d rows)" % len(op.rows),
                                operation="INSERT",
                                mode="db",
                            )
                            await cur.execute(sql, params)
                        else:
                            sql, params = self._op_to_oracle_sql(op)
                            log_event(
                                logger,
                                "debug",
                                "OUTPUT",
                                "executing SQL",
                                operation=op.op_type,
                                mode="db",
                            )
                            await cur.execute(sql, params)
                await conn.commit()
            except Exception:
                await conn.rollback()
                raise

    # ── Error classification ────────────────────────────────────────────

    def _is_transient(self, exc: Exception) -> bool:
        if oracledb is None:
            return False
        if isinstance(exc, (ConnectionError, OSError, TimeoutError)):
            return True
        code = _ora_error_code(exc)
        if code is not None:
            return code in _TRANSIENT_ORA_CODES
        return False

    def _error_class(self, exc: Exception) -> str:
        if oracledb is None:
            return "unknown"
        if isinstance(exc, TimeoutError):
            return "timeout"
        if isinstance(exc, (ConnectionError, OSError)):
            return "connection"
        code = _ora_error_code(exc)
        if code is not None:
            if code in (3113, 3114, 3135, 12170, 12541, 12543):
                return "connection"
            if code == 60:
                return "deadlock"
            if code == 1:  # ORA-00001: unique constraint violated
                return "constraint_violation"
            if code in (2291, 2292):  # FK violations
                return "constraint_violation"
            if code in (1722, 1858, 1861):  # type conversion errors
                return "data_type"
            if code in (942, 904, 903):  # table/column/schema not found
                return "syntax_or_schema"
            return f"ora_{code}"
        return "unknown"

    # ── Health check ────────────────────────────────────────────────────

    async def _test_connection(self) -> None:
        pool = self._pool
        if pool is None:
            raise ConnectionError("Oracle pool is not connected")
        async with pool.acquire() as conn:
            async with conn.cursor() as cur:
                await cur.execute("SELECT 1 FROM DUAL")
        ic("_test_connection: OK", self._dsn)
        log_event(
            logger,
            "info",
            "OUTPUT",
            "Oracle reachable",
            host=self._dsn,
            mode="db",
        )


# ── Introspection (standalone functions, not part of the forwarder) ──────


async def introspect_tables(ora_cfg: dict) -> list[dict]:
    """
    Connect to Oracle and return all tables with their columns.

    Returns the same structure as db_postgres.introspect_tables:
    [
        {
            "table_name": "ORDERS",
            "schema": "HR",
            "columns": [
                {"name": "ID", "type": "NUMBER", "display_type": "NUMBER(10,0)",
                 "nullable": false, "default": null},
                ...
            ],
            "primary_key": ["ID"],
            "foreign_keys": [
                {"column": "CUSTOMER_ID", "references_table": "CUSTOMERS",
                 "references_column": "ID"}
            ]
        },
        ...
    ]
    """
    if oracledb is None:
        raise RuntimeError("oracledb library not installed – pip install oracledb")

    dsn = ora_cfg.get("dsn", "")
    if not dsn:
        host = ora_cfg.get("host", "localhost")
        port = ora_cfg.get("port", 1521)
        database = ora_cfg.get("database", "")
        dsn = f"{host}:{port}/{database}"

    conn = await oracledb.connect_async(
        user=ora_cfg.get("user", ""),
        password=ora_cfg.get("password", ""),
        dsn=dsn,
    )

    try:
        schema = (ora_cfg.get("schema", "") or ora_cfg.get("user", "")).upper()

        cur = conn.cursor()
        try:
            # Get all tables
            await cur.execute(
                "SELECT table_name FROM all_tables WHERE owner = :1 ORDER BY table_name",
                [schema],
            )
            table_rows = await cur.fetchall()

            result = []
            for (table_name,) in table_rows:
                # Get columns
                await cur.execute(
                    "SELECT column_name, data_type, data_length, data_precision, "
                    "data_scale, nullable, data_default "
                    "FROM all_tab_columns "
                    "WHERE owner = :1 AND table_name = :2 "
                    "ORDER BY column_id",
                    [schema, table_name],
                )
                col_rows = await cur.fetchall()

                columns = []
                for (
                    col_name,
                    data_type,
                    data_length,
                    data_precision,
                    data_scale,
                    nullable,
                    default_val,
                ) in col_rows:
                    display_type = data_type
                    if data_type in ("NUMBER",) and data_precision is not None:
                        display_type = (
                            f"{data_type}({data_precision},{data_scale or 0})"
                        )
                    elif data_type in (
                        "VARCHAR2",
                        "CHAR",
                        "NVARCHAR2",
                        "NCHAR",
                        "RAW",
                    ):
                        display_type = f"{data_type}({data_length})"

                    columns.append(
                        {
                            "name": col_name,
                            "type": data_type,
                            "display_type": display_type,
                            "nullable": nullable == "Y",
                            "default": default_val.strip() if default_val else None,
                        }
                    )

                # Get primary key columns
                await cur.execute(
                    "SELECT cols.column_name "
                    "FROM all_constraints cons "
                    "JOIN all_cons_columns cols "
                    "  ON cons.constraint_name = cols.constraint_name "
                    "  AND cons.owner = cols.owner "
                    "WHERE cons.owner = :1 AND cons.table_name = :2 "
                    "  AND cons.constraint_type = 'P' "
                    "ORDER BY cols.position",
                    [schema, table_name],
                )
                pk_rows = await cur.fetchall()
                pk_cols = [r[0] for r in pk_rows]

                # Get foreign keys
                await cur.execute(
                    "SELECT a.column_name, "
                    "  c_pk.table_name AS references_table, "
                    "  b.column_name AS references_column "
                    "FROM all_cons_columns a "
                    "JOIN all_constraints c "
                    "  ON a.constraint_name = c.constraint_name "
                    "  AND a.owner = c.owner "
                    "JOIN all_constraints c_pk "
                    "  ON c.r_constraint_name = c_pk.constraint_name "
                    "  AND c.r_owner = c_pk.owner "
                    "JOIN all_cons_columns b "
                    "  ON c_pk.constraint_name = b.constraint_name "
                    "  AND c_pk.owner = b.owner "
                    "  AND a.position = b.position "
                    "WHERE c.owner = :1 AND c.table_name = :2 "
                    "  AND c.constraint_type = 'R'",
                    [schema, table_name],
                )
                fk_rows = await cur.fetchall()
                fks = [
                    {
                        "column": r[0],
                        "references_table": r[1],
                        "references_column": r[2],
                    }
                    for r in fk_rows
                ]

                result.append(
                    {
                        "table_name": table_name,
                        "schema": schema,
                        "columns": columns,
                        "primary_key": pk_cols,
                        "foreign_keys": fks,
                    }
                )

            return result
        finally:
            await cur.close()
    finally:
        await conn.close()


async def introspect_single_table(ora_cfg: dict, table_name: str) -> dict | None:
    """Introspect a single table. Returns the table dict or None."""
    tables = await introspect_tables(ora_cfg)
    for t in tables:
        if t["table_name"] == table_name:
            return t
    return None
