"""
PostgreSQL output module for changes_worker.

Uses asyncpg for async connection pooling and executes SQL statements
generated by the SchemaMapper based on mapping definitions.
"""

import asyncio
import json
import logging
import time
from collections import deque

logger = logging.getLogger("changes_worker")

# Lazy import asyncpg
try:
    import asyncpg
except ImportError:
    asyncpg = None


class PostgresOutputForwarder:
    """
    Async PostgreSQL output forwarder.

    Receives JSON documents from the changes feed, maps them to SQL
    operations via SchemaMapper, and executes against PostgreSQL.
    """

    def __init__(self, out_cfg: dict, dry_run: bool = False, metrics=None):
        if asyncpg is None:
            raise RuntimeError("asyncpg library not installed – pip install asyncpg")

        self._mode = "postgres"
        # Support both output.db.{host,…} (UI config) and output.postgres.{host,…}
        pg_cfg = out_cfg.get("db", None) or out_cfg.get("postgres", {})
        self._host = pg_cfg.get("host", "localhost")
        self._port = pg_cfg.get("port", 5432)
        self._database = pg_cfg.get("database", "")
        self._user = pg_cfg.get("username", pg_cfg.get("user", "postgres"))
        self._password = pg_cfg.get("password", "")
        self._schema = pg_cfg.get("schema", "public")
        self._ssl = pg_cfg.get("ssl", False)
        self._pool_min = pg_cfg.get("pool_min", 2)
        self._pool_max = pg_cfg.get("pool_max", 10)

        self._dry_run = dry_run
        self._halt_on_failure = out_cfg.get("halt_on_failure", True)
        self._metrics = metrics

        self._pool: asyncpg.Pool | None = None
        self._mappers: list = []  # List of SchemaMapper instances
        # Support mapping_file (single file) or schema_mappings.path (directory)
        self._mapping_file = out_cfg.get("mapping_file", "")
        sm = pg_cfg.get("schema_mappings", {})
        self._mappings_dir = sm.get("path", "") if sm.get("enabled") else ""

        # Response time tracking
        self._resp_times: deque[float] = deque(maxlen=10000)
        self._lock = asyncio.Lock()

    async def connect(self) -> None:
        """Create the connection pool and load the schema mapping."""
        ssl_ctx = self._ssl
        if isinstance(self._ssl, bool) and self._ssl:
            import ssl as _ssl
            ssl_ctx = _ssl.create_default_context()
            ssl_ctx.check_hostname = False
            ssl_ctx.verify_mode = _ssl.CERT_NONE

        self._pool = await asyncpg.create_pool(
            host=self._host,
            port=self._port,
            database=self._database,
            user=self._user,
            password=self._password,
            min_size=self._pool_min,
            max_size=self._pool_max,
            ssl=ssl_ctx if self._ssl else None,
        )
        logger.info("PostgreSQL pool created: %s:%d/%s (pool %d–%d)",
                     self._host, self._port, self._database,
                     self._pool_min, self._pool_max)

        # Load mappings from filesystem (bind-mounted, shared with admin-ui)
        from schema.mapper import SchemaMapper
        from pathlib import Path

        if self._mappings_dir:
            mdir = Path(self._mappings_dir)
            if mdir.is_dir():
                for f in sorted(mdir.glob("*.json")):
                    try:
                        raw = json.loads(f.read_text())
                        meta = raw.get("_meta", {})
                        if not meta.get("active", True):
                            logger.info("Skipping inactive mapping: %s", f)
                            continue
                    except (json.JSONDecodeError, OSError):
                        pass
                    self._mappers.append(SchemaMapper.from_file(f))
                    logger.info("Loaded schema mapping from %s", f)
        if self._mapping_file:
            self._mappers.append(SchemaMapper.from_file(self._mapping_file))
            logger.info("Loaded schema mapping from %s", self._mapping_file)

        if not self._mappers:
            logger.warning("No schema mappings loaded – documents will be skipped")

    async def close(self) -> None:
        """Close the connection pool."""
        if self._pool:
            await self._pool.close()
            logger.info("PostgreSQL pool closed")

    async def send(self, doc: dict, method: str = "PUT") -> dict:
        """
        Process a single document: map to SQL ops and execute.
        Returns result dict with 'ok' bool.
        """
        doc_id = doc.get("_id", doc.get("id", "unknown"))
        is_delete = method == "DELETE"

        if not self._mappers:
            logger.warning("No schema mapping loaded – skipping doc %s", doc_id)
            return {"ok": False, "doc_id": doc_id, "error": "no_mapping"}

        # Find the first matching mapper
        mapper = None
        for m in self._mappers:
            if m.matches(doc):
                mapper = m
                break
        if not mapper:
            logger.debug("Doc %s does not match any mapping filter – skipping", doc_id)
            return {"ok": True, "doc_id": doc_id, "skipped": True}

        ops = mapper.map_document(doc, is_delete=is_delete)
        if not ops:
            return {"ok": True, "doc_id": doc_id, "ops": 0}

        if self._dry_run:
            for op in ops:
                sql, params = op.to_sql()
                logger.info("[DRY RUN] %s | params=%s", sql, params)
            return {"ok": True, "doc_id": doc_id, "ops": len(ops), "dry_run": True}

        t_start = time.monotonic()
        try:
            async with self._pool.acquire() as conn:
                async with conn.transaction():
                    for op in ops:
                        sql, params = op.to_sql()
                        logger.debug("SQL: %s | params=%s", sql, params)
                        await conn.execute(sql, *params)

            elapsed_ms = (time.monotonic() - t_start) * 1000
            async with self._lock:
                self._resp_times.append(elapsed_ms)
            if self._metrics:
                self._metrics.inc("output_requests_total")
                self._metrics.inc("output_success_total")
                self._metrics.record_output_response_time(elapsed_ms / 1000)

            logger.debug("PostgreSQL: %d ops for %s (%.1fms)", len(ops), doc_id, elapsed_ms)
            return {"ok": True, "doc_id": doc_id, "ops": len(ops), "elapsed_ms": round(elapsed_ms, 1)}

        except Exception as exc:
            elapsed_ms = (time.monotonic() - t_start) * 1000
            if self._metrics:
                self._metrics.inc("output_requests_total")
                self._metrics.inc("output_errors_total")
            logger.error("PostgreSQL error for doc %s: %s", doc_id, exc)

            if self._halt_on_failure:
                from rest import OutputEndpointDown
                raise OutputEndpointDown(
                    f"PostgreSQL error for {doc_id}: {exc}"
                ) from exc
            return {"ok": False, "doc_id": doc_id, "error": str(exc)[:500]}

    async def test_reachable(self) -> bool:
        """Test that the PostgreSQL server is reachable."""
        try:
            if not self._pool:
                await self.connect()
            async with self._pool.acquire() as conn:
                await conn.fetchval("SELECT 1")
            logger.info("PostgreSQL reachable: %s:%d/%s", self._host, self._port, self._database)
            return True
        except Exception as exc:
            logger.error("PostgreSQL unreachable: %s", exc)
            return False

    def log_stats(self) -> None:
        """Log accumulated response time statistics."""
        if not self._resp_times:
            return
        n = len(self._resp_times)
        avg = sum(self._resp_times) / n
        lo = min(self._resp_times)
        hi = max(self._resp_times)
        logger.info("PostgreSQL stats: %d ops | avg=%.1fms | min=%.1fms | max=%.1fms",
                     n, avg, lo, hi)


async def introspect_tables(pg_cfg: dict) -> list[dict]:
    """
    Connect to PostgreSQL and return all tables with their columns.

    Returns: [
        {
            "table_name": "orders",
            "schema": "public",
            "columns": [
                {"name": "id", "type": "integer", "nullable": false, "default": "nextval(...)"},
                {"name": "status", "type": "character varying", "nullable": true, "default": null},
                ...
            ],
            "primary_key": ["id"],
            "foreign_keys": [
                {"column": "customer_id", "references_table": "customers", "references_column": "id"}
            ]
        },
        ...
    ]
    """
    if asyncpg is None:
        raise RuntimeError("asyncpg library not installed – pip install asyncpg")

    ssl_ctx = None
    if pg_cfg.get("ssl"):
        import ssl as _ssl
        ssl_ctx = _ssl.create_default_context()
        ssl_ctx.check_hostname = False
        ssl_ctx.verify_mode = _ssl.CERT_NONE

    conn = await asyncpg.connect(
        host=pg_cfg.get("host", "localhost"),
        port=pg_cfg.get("port", 5432),
        database=pg_cfg.get("database", ""),
        user=pg_cfg.get("user", "postgres"),
        password=pg_cfg.get("password", ""),
        ssl=ssl_ctx,
    )

    try:
        schema = pg_cfg.get("schema", "public")

        # Get all tables
        tables_rows = await conn.fetch("""
            SELECT table_name
            FROM information_schema.tables
            WHERE table_schema = $1 AND table_type = 'BASE TABLE'
            ORDER BY table_name
        """, schema)

        result = []
        for trow in tables_rows:
            table_name = trow["table_name"]

            # Get columns
            col_rows = await conn.fetch("""
                SELECT column_name, data_type, udt_name, is_nullable,
                       column_default, character_maximum_length,
                       numeric_precision, numeric_scale
                FROM information_schema.columns
                WHERE table_schema = $1 AND table_name = $2
                ORDER BY ordinal_position
            """, schema, table_name)

            columns = []
            for c in col_rows:
                col_type = c["data_type"]
                # Use udt_name for user-defined types (e.g., varchar shows as "character varying")
                if col_type == "USER-DEFINED":
                    col_type = c["udt_name"]
                display_type = col_type
                if c["character_maximum_length"]:
                    display_type += f"({c['character_maximum_length']})"
                elif c["numeric_precision"] and col_type in ("numeric", "decimal"):
                    display_type += f"({c['numeric_precision']},{c['numeric_scale'] or 0})"

                columns.append({
                    "name": c["column_name"],
                    "type": col_type,
                    "display_type": display_type,
                    "nullable": c["is_nullable"] == "YES",
                    "default": c["column_default"],
                })

            # Get primary key columns
            pk_rows = await conn.fetch("""
                SELECT kcu.column_name
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                    ON tc.constraint_name = kcu.constraint_name
                    AND tc.table_schema = kcu.table_schema
                WHERE tc.table_schema = $1 AND tc.table_name = $2
                    AND tc.constraint_type = 'PRIMARY KEY'
                ORDER BY kcu.ordinal_position
            """, schema, table_name)
            pk_cols = [r["column_name"] for r in pk_rows]

            # Get foreign keys
            fk_rows = await conn.fetch("""
                SELECT kcu.column_name,
                       ccu.table_name AS references_table,
                       ccu.column_name AS references_column
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                    ON tc.constraint_name = kcu.constraint_name
                    AND tc.table_schema = kcu.table_schema
                JOIN information_schema.constraint_column_usage ccu
                    ON tc.constraint_name = ccu.constraint_name
                    AND tc.table_schema = ccu.table_schema
                WHERE tc.table_schema = $1 AND tc.table_name = $2
                    AND tc.constraint_type = 'FOREIGN KEY'
            """, schema, table_name)
            fks = [
                {"column": r["column_name"],
                 "references_table": r["references_table"],
                 "references_column": r["references_column"]}
                for r in fk_rows
            ]

            result.append({
                "table_name": table_name,
                "schema": schema,
                "columns": columns,
                "primary_key": pk_cols,
                "foreign_keys": fks,
            })

        return result
    finally:
        await conn.close()


async def introspect_single_table(pg_cfg: dict, table_name: str) -> dict | None:
    """Introspect a single table. Returns the table dict or None."""
    tables = await introspect_tables(pg_cfg)
    for t in tables:
        if t["table_name"] == table_name:
            return t
    return None
