"""
PostgreSQL output module for changes_worker.

Uses asyncpg for async connection pooling and executes SQL statements
generated by the SchemaMapper based on mapping definitions.
"""

import asyncio
import json
import logging
import time
from collections import deque

logger = logging.getLogger("changes_worker")

# Lazy import asyncpg
try:
    import asyncpg
except ImportError:
    asyncpg = None

# -- asyncpg error classification ------------------------------------------------
# Transient errors are worth retrying (connection hiccups, deadlocks, serialization).
# Permanent errors should go straight to the DLQ (constraint violations, bad types).
_TRANSIENT_SQLSTATES = frozenset({
    "40001",  # serialization_failure
    "40P01",  # deadlock_detected
    "08000",  # connection_exception
    "08003",  # connection_does_not_exist
    "08006",  # connection_failure
    "57P01",  # admin_shutdown
    "57P02",  # crash_shutdown
    "57P03",  # cannot_connect_now
})


def _is_transient(exc: Exception) -> bool:
    """Return True if the asyncpg exception is transient and worth retrying."""
    if asyncpg is None:
        return False
    if isinstance(exc, (asyncpg.InterfaceError,
                        asyncpg.ConnectionDoesNotExistError,
                        ConnectionError,
                        OSError,
                        TimeoutError)):
        return True
    if isinstance(exc, asyncpg.PostgresError):
        return getattr(exc, "sqlstate", None) in _TRANSIENT_SQLSTATES
    return False


def _error_class(exc: Exception) -> str:
    """Return a short classification string for the error."""
    if asyncpg is None:
        return "unknown"
    if isinstance(exc, (asyncpg.InterfaceError,
                        asyncpg.ConnectionDoesNotExistError,
                        ConnectionError, OSError)):
        return "connection"
    if isinstance(exc, TimeoutError):
        return "timeout"
    if isinstance(exc, asyncpg.PostgresError):
        state = getattr(exc, "sqlstate", "") or ""
        if state.startswith("23"):
            return "constraint_violation"
        if state in ("40001", "40P01"):
            return "deadlock"
        if state.startswith("08") or state.startswith("57"):
            return "connection"
        if state.startswith("42"):
            return "syntax_or_schema"
        if state.startswith("22"):
            return "data_type"
        return f"pg_{state}" if state else "unknown_pg"
    return "unknown"


class PostgresOutputForwarder:
    """
    Async PostgreSQL output forwarder.

    Receives JSON documents from the changes feed, maps them to SQL
    operations via SchemaMapper, and executes against PostgreSQL.
    """

    def __init__(self, out_cfg: dict, dry_run: bool = False, metrics=None):
        if asyncpg is None:
            raise RuntimeError("asyncpg library not installed – pip install asyncpg")

        self._mode = "postgres"
        # Support both output.db.{host,…} (UI config) and output.postgres.{host,…}
        pg_cfg = out_cfg.get("db", None) or out_cfg.get("postgres", {})
        self._host = pg_cfg.get("host", "localhost")
        self._port = pg_cfg.get("port", 5432)
        self._database = pg_cfg.get("database", "")
        self._user = pg_cfg.get("username", pg_cfg.get("user", "postgres"))
        self._password = pg_cfg.get("password", "")
        self._schema = pg_cfg.get("schema", "public")
        self._ssl = pg_cfg.get("ssl", False)
        self._pool_min = pg_cfg.get("pool_min", 2)
        self._pool_max = pg_cfg.get("pool_max", 10)

        self._dry_run = dry_run
        self._halt_on_failure = out_cfg.get("halt_on_failure", True)
        self._max_retries = pg_cfg.get("max_retries", 3)
        self._backoff_base = pg_cfg.get("backoff_base_seconds", 0.5)
        self._backoff_max = pg_cfg.get("backoff_max_seconds", 10)
        self._metrics = metrics

        self._pool: asyncpg.Pool | None = None
        self._mappers: list = []  # List of SchemaMapper instances
        # Support mapping_file (single file) or schema_mappings.path (directory)
        self._mapping_file = out_cfg.get("mapping_file", "")
        sm = pg_cfg.get("schema_mappings", {})
        self._mappings_dir = sm.get("path", "") if sm.get("enabled") else ""

        # Response time tracking
        self._resp_times: deque[float] = deque(maxlen=10000)
        self._lock = asyncio.Lock()

    async def connect(self) -> None:
        """Create the connection pool and load the schema mapping."""
        ssl_ctx = self._ssl
        if isinstance(self._ssl, bool) and self._ssl:
            import ssl as _ssl
            ssl_ctx = _ssl.create_default_context()
            ssl_ctx.check_hostname = False
            ssl_ctx.verify_mode = _ssl.CERT_NONE

        self._pool = await asyncpg.create_pool(
            host=self._host,
            port=self._port,
            database=self._database,
            user=self._user,
            password=self._password,
            min_size=self._pool_min,
            max_size=self._pool_max,
            ssl=ssl_ctx if self._ssl else None,
        )
        logger.info("PostgreSQL pool created: %s:%d/%s (pool %d–%d)",
                     self._host, self._port, self._database,
                     self._pool_min, self._pool_max)

        # Load mappings – prefer CBL (single source of truth), fall back to filesystem
        from schema.mapper import SchemaMapper
        from pathlib import Path
        import json as _json

        cbl_loaded = False
        try:
            from cbl_store import USE_CBL, CBLStore
            if USE_CBL:
                entries = CBLStore().list_mappings()
                for entry in entries:
                    name = entry.get("name", "")
                    if name.endswith(".meta.json"):
                        continue
                    raw = entry.get("content", "")
                    if not raw:
                        continue
                    data = _json.loads(raw) if isinstance(raw, str) else raw
                    data["_source_name"] = name
                    self._mappers.append(SchemaMapper(data))
                    logger.info("Loaded schema mapping from CBL: %s", name)
                cbl_loaded = True
        except Exception as exc:
            logger.warning("Could not load mappings from CBL (%s) – falling back to filesystem", exc)

        if not cbl_loaded:
            if self._mappings_dir:
                mdir = Path(self._mappings_dir)
                if mdir.is_dir():
                    for f in sorted(mdir.glob("*.json")):
                        if f.name.endswith(".meta.json"):
                            continue
                        try:
                            raw = json.loads(f.read_text())
                            meta = raw.get("_meta", {})
                            if not meta.get("active", True):
                                logger.info("Skipping inactive mapping: %s", f)
                                continue
                        except (json.JSONDecodeError, OSError):
                            pass
                        self._mappers.append(SchemaMapper.from_file(f))
                        logger.info("Loaded schema mapping from %s", f)
            if self._mapping_file:
                self._mappers.append(SchemaMapper.from_file(self._mapping_file))
                logger.info("Loaded schema mapping from %s", self._mapping_file)

        if not self._mappers:
            logger.warning("No schema mappings loaded – documents will be skipped")

        # Warn about duplicate match filters (first-match wins, rest are shadowed)
        seen_matches = {}
        for m in self._mappers:
            key = f"{m.match.get('field', '')}={m.match.get('value', '')}"
            src = m.mapping.get("_source_name", "?")
            if key in seen_matches:
                logger.warning(
                    "DUPLICATE MAPPING: '%s' and '%s' both match %s — "
                    "only '%s' will be used (first-match wins)",
                    seen_matches[key], src, key, seen_matches[key])
            else:
                seen_matches[key] = src

    async def close(self) -> None:
        """Close the connection pool."""
        if self._pool:
            await self._pool.close()
            logger.info("PostgreSQL pool closed")

    async def send(self, doc: dict, method: str = "PUT") -> dict:
        """
        Process a single document: map to SQL ops and execute.

        Transient errors (connection loss, deadlocks) are retried with
        exponential backoff.  Permanent errors (constraint violations,
        type mismatches) are returned immediately so the caller can
        route them to the dead-letter queue.

        Returns result dict with 'ok' bool plus 'retryable' and
        'error_class' on failure.
        """
        if doc is None:
            logger.debug("Received None doc – skipping")
            if self._metrics:
                self._metrics.inc("output_skipped_total")
            return {"ok": True, "doc_id": "unknown", "skipped": True}

        doc_id = doc.get("_id", doc.get("id", "unknown"))
        is_delete = method == "DELETE"

        if not self._mappers:
            logger.warning("No schema mapping loaded – skipping doc %s", doc_id)
            if self._metrics:
                self._metrics.inc("output_skipped_total")
            return {"ok": False, "doc_id": doc_id, "error": "no_mapping",
                    "retryable": False, "error_class": "config"}

        # Find the first matching mapper
        mapper = None
        for m in self._mappers:
            if m.matches(doc):
                mapper = m
                break
        if not mapper:
            logger.debug("Doc %s does not match any mapping filter – skipping", doc_id)
            if self._metrics:
                self._metrics.inc("output_skipped_total")
                self._metrics.inc("mapper_skipped_total")
            return {"ok": True, "doc_id": doc_id, "skipped": True}

        try:
            ops = mapper.map_document(doc, is_delete=is_delete)
        except Exception as exc:
            if self._metrics:
                self._metrics.inc("output_requests_total")
                self._metrics.inc("output_errors_total")
                self._metrics.inc("mapper_errors_total")
                self._metrics.inc("db_permanent_errors_total")
            logger.error("Mapping error for doc %s: %s", doc_id, exc)
            return {"ok": False, "doc_id": doc_id,
                    "error": f"mapping_error: {exc!s}"[:500],
                    "retryable": False, "error_class": "mapping"}

        if self._metrics:
            self._metrics.inc("mapper_matched_total")

        if not ops:
            if self._metrics:
                self._metrics.inc("output_skipped_total")
            return {"ok": True, "doc_id": doc_id, "ops": 0}

        if self._dry_run:
            for op in ops:
                sql, params = op.to_sql()
                logger.info("[DRY RUN] %s | params=%s", sql, params)
            return {"ok": True, "doc_id": doc_id, "ops": len(ops), "dry_run": True}

        # -- Execute with retry for transient errors --
        t_start = time.monotonic()
        last_exc: Exception | None = None

        for attempt in range(1, self._max_retries + 1):
            try:
                async with self._pool.acquire() as conn:
                    async with conn.transaction():
                        for op in ops:
                            sql, params = op.to_sql()
                            logger.debug("SQL: %s | params=%s", sql, params)
                            await conn.execute(sql, *params)

                # Success
                elapsed_ms = (time.monotonic() - t_start) * 1000
                async with self._lock:
                    self._resp_times.append(elapsed_ms)
                if self._metrics:
                    self._metrics.inc("output_requests_total")
                    self._metrics.inc("output_success_total")
                    self._metrics.inc("mapper_ops_total", len(ops))
                    self._metrics.record_output_response_time(elapsed_ms / 1000)

                logger.debug("PostgreSQL: %d ops for %s (%.1fms)", len(ops), doc_id, elapsed_ms)
                return {"ok": True, "doc_id": doc_id, "ops": len(ops),
                        "elapsed_ms": round(elapsed_ms, 1)}

            except Exception as exc:
                last_exc = exc
                eclass = _error_class(exc)

                if not _is_transient(exc):
                    # Permanent error — no retry, return immediately
                    elapsed_ms = (time.monotonic() - t_start) * 1000
                    if self._metrics:
                        self._metrics.inc("output_requests_total")
                        self._metrics.inc("output_errors_total")
                        self._metrics.inc("db_permanent_errors_total")
                    logger.error("PostgreSQL permanent error for doc %s [%s]: %s",
                                 doc_id, eclass, exc)

                    if self._halt_on_failure:
                        from rest import OutputEndpointDown
                        raise OutputEndpointDown(
                            f"PostgreSQL error for {doc_id} [{eclass}]: {exc}"
                        ) from exc
                    return {"ok": False, "doc_id": doc_id,
                            "error": str(exc)[:500],
                            "retryable": False, "error_class": eclass}

                # Transient error — retry
                if self._metrics:
                    self._metrics.inc("db_transient_errors_total")
                    self._metrics.inc("db_retries_total")

                # Attempt pool reconnect on connection-level errors
                if eclass == "connection":
                    try:
                        logger.warning("PostgreSQL connection error – reconnecting pool "
                                       "(attempt %d/%d): %s", attempt, self._max_retries, exc)
                        await self._pool.close()
                        await self.connect()
                        if self._metrics:
                            self._metrics.inc("db_pool_reconnects_total")
                    except Exception as reconn_exc:
                        logger.error("Pool reconnect failed: %s", reconn_exc)
                        if attempt == self._max_retries:
                            break
                else:
                    logger.warning("PostgreSQL transient error for doc %s [%s] "
                                   "(attempt %d/%d): %s",
                                   doc_id, eclass, attempt, self._max_retries, exc)

                if attempt < self._max_retries:
                    delay = min(self._backoff_base * (2 ** (attempt - 1)),
                                self._backoff_max)
                    await asyncio.sleep(delay)

        # All retries exhausted
        elapsed_ms = (time.monotonic() - t_start) * 1000
        eclass = _error_class(last_exc) if last_exc else "unknown"
        if self._metrics:
            self._metrics.inc("output_requests_total")
            self._metrics.inc("output_errors_total")
            self._metrics.inc("db_retry_exhausted_total")
        logger.error("PostgreSQL retries exhausted for doc %s [%s] after %d attempts: %s",
                     doc_id, eclass, self._max_retries, last_exc)

        if self._halt_on_failure:
            from rest import OutputEndpointDown
            raise OutputEndpointDown(
                f"PostgreSQL retries exhausted for {doc_id} [{eclass}]: {last_exc}"
            ) from last_exc
        return {"ok": False, "doc_id": doc_id,
                "error": str(last_exc)[:500],
                "retryable": False, "error_class": eclass}

    async def test_reachable(self) -> bool:
        """Test that the PostgreSQL server is reachable."""
        try:
            if not self._pool:
                await self.connect()
            async with self._pool.acquire() as conn:
                await conn.fetchval("SELECT 1")
            logger.info("PostgreSQL reachable: %s:%d/%s", self._host, self._port, self._database)
            return True
        except Exception as exc:
            logger.error("PostgreSQL unreachable: %s", exc)
            return False

    def log_stats(self) -> None:
        """Log accumulated response time statistics."""
        if not self._resp_times:
            return
        n = len(self._resp_times)
        avg = sum(self._resp_times) / n
        lo = min(self._resp_times)
        hi = max(self._resp_times)
        logger.info("PostgreSQL stats: %d ops | avg=%.1fms | min=%.1fms | max=%.1fms",
                     n, avg, lo, hi)


async def introspect_tables(pg_cfg: dict) -> list[dict]:
    """
    Connect to PostgreSQL and return all tables with their columns.

    Returns: [
        {
            "table_name": "orders",
            "schema": "public",
            "columns": [
                {"name": "id", "type": "integer", "nullable": false, "default": "nextval(...)"},
                {"name": "status", "type": "character varying", "nullable": true, "default": null},
                ...
            ],
            "primary_key": ["id"],
            "foreign_keys": [
                {"column": "customer_id", "references_table": "customers", "references_column": "id"}
            ]
        },
        ...
    ]
    """
    if asyncpg is None:
        raise RuntimeError("asyncpg library not installed – pip install asyncpg")

    ssl_ctx = None
    if pg_cfg.get("ssl"):
        import ssl as _ssl
        ssl_ctx = _ssl.create_default_context()
        ssl_ctx.check_hostname = False
        ssl_ctx.verify_mode = _ssl.CERT_NONE

    conn = await asyncpg.connect(
        host=pg_cfg.get("host", "localhost"),
        port=pg_cfg.get("port", 5432),
        database=pg_cfg.get("database", ""),
        user=pg_cfg.get("user", "postgres"),
        password=pg_cfg.get("password", ""),
        ssl=ssl_ctx,
    )

    try:
        schema = pg_cfg.get("schema", "public")

        # Get all tables
        tables_rows = await conn.fetch("""
            SELECT table_name
            FROM information_schema.tables
            WHERE table_schema = $1 AND table_type = 'BASE TABLE'
            ORDER BY table_name
        """, schema)

        result = []
        for trow in tables_rows:
            table_name = trow["table_name"]

            # Get columns
            col_rows = await conn.fetch("""
                SELECT column_name, data_type, udt_name, is_nullable,
                       column_default, character_maximum_length,
                       numeric_precision, numeric_scale
                FROM information_schema.columns
                WHERE table_schema = $1 AND table_name = $2
                ORDER BY ordinal_position
            """, schema, table_name)

            columns = []
            for c in col_rows:
                col_type = c["data_type"]
                # Use udt_name for user-defined types (e.g., varchar shows as "character varying")
                if col_type == "USER-DEFINED":
                    col_type = c["udt_name"]
                display_type = col_type
                if c["character_maximum_length"]:
                    display_type += f"({c['character_maximum_length']})"
                elif c["numeric_precision"] and col_type in ("numeric", "decimal"):
                    display_type += f"({c['numeric_precision']},{c['numeric_scale'] or 0})"

                columns.append({
                    "name": c["column_name"],
                    "type": col_type,
                    "display_type": display_type,
                    "nullable": c["is_nullable"] == "YES",
                    "default": c["column_default"],
                })

            # Get primary key columns
            pk_rows = await conn.fetch("""
                SELECT kcu.column_name
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                    ON tc.constraint_name = kcu.constraint_name
                    AND tc.table_schema = kcu.table_schema
                WHERE tc.table_schema = $1 AND tc.table_name = $2
                    AND tc.constraint_type = 'PRIMARY KEY'
                ORDER BY kcu.ordinal_position
            """, schema, table_name)
            pk_cols = [r["column_name"] for r in pk_rows]

            # Get foreign keys
            fk_rows = await conn.fetch("""
                SELECT kcu.column_name,
                       ccu.table_name AS references_table,
                       ccu.column_name AS references_column
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                    ON tc.constraint_name = kcu.constraint_name
                    AND tc.table_schema = kcu.table_schema
                JOIN information_schema.constraint_column_usage ccu
                    ON tc.constraint_name = ccu.constraint_name
                    AND tc.table_schema = ccu.table_schema
                WHERE tc.table_schema = $1 AND tc.table_name = $2
                    AND tc.constraint_type = 'FOREIGN KEY'
            """, schema, table_name)
            fks = [
                {"column": r["column_name"],
                 "references_table": r["references_table"],
                 "references_column": r["references_column"]}
                for r in fk_rows
            ]

            result.append({
                "table_name": table_name,
                "schema": schema,
                "columns": columns,
                "primary_key": pk_cols,
                "foreign_keys": fks,
            })

        return result
    finally:
        await conn.close()


async def introspect_single_table(pg_cfg: dict, table_name: str) -> dict | None:
    """Introspect a single table. Returns the table dict or None."""
    tables = await introspect_tables(pg_cfg)
    for t in tables:
        if t["table_name"] == table_name:
            return t
    return None
