"""
PostgreSQL output module for changes_worker.

Uses asyncpg for async connection pooling and executes SQL statements
generated by the SchemaMapper based on mapping definitions.
"""

import asyncio
import logging

from db.db_base import BaseOutputForwarder, group_insert_ops, _MultiRowInsert
from pipeline.pipeline_logging import log_event

try:
    from icecream import ic
except ImportError:
    ic = lambda *a, **kw: None  # noqa: E731

logger = logging.getLogger("changes_worker")

# Lazy import asyncpg
try:
    import asyncpg
except ImportError:
    asyncpg = None

# -- asyncpg error classification ------------------------------------------------
# Transient errors are worth retrying (connection hiccups, deadlocks, serialization).
# Permanent errors should go straight to the DLQ (constraint violations, bad types).
_TRANSIENT_SQLSTATES = frozenset(
    {
        # Serialization / deadlock
        "40001",  # serialization_failure
        "40P01",  # deadlock_detected
        # Connection
        "08000",  # connection_exception
        "08001",  # sqlclient_unable_to_establish_sqlconnection
        "08003",  # connection_does_not_exist
        "08004",  # sqlserver_rejected_establishment_of_sqlconnection
        "08006",  # connection_failure
        # Resource exhaustion
        "53000",  # insufficient_resources
        "53100",  # disk_full
        "53200",  # out_of_memory
        "53300",  # too_many_connections
        "53400",  # configuration_limit_exceeded
        # Lock contention
        "55P03",  # lock_not_available
        # Server lifecycle
        "57P01",  # admin_shutdown
        "57P02",  # crash_shutdown
        "57P03",  # cannot_connect_now
        # Schema (may be recreated)
        "42P01",  # undefined_table — table may be recreated
    }
)


class PostgresOutputForwarder(BaseOutputForwarder):
    """
    Async PostgreSQL output forwarder.

    Receives JSON documents from the changes feed, maps them to SQL
    operations via SchemaMapper, and executes against PostgreSQL.
    """

    @property
    def _engine(self) -> str:
        return "postgres"

    def _get_engine_cfg(self, out_cfg: dict) -> dict:
        nested = out_cfg.get("db", None) or out_cfg.get("postgres", None)
        if nested:
            return nested
        # v2 job outputs store connection fields at the top level
        if "host" in out_cfg or "port" in out_cfg or "database" in out_cfg:
            return out_cfg
        return {}

    def __init__(self, out_cfg: dict, dry_run: bool = False, metrics=None):
        if asyncpg is None:
            raise RuntimeError("asyncpg library not installed – pip install asyncpg")

        super().__init__(out_cfg, dry_run, metrics=metrics)

        pg_cfg = self._get_engine_cfg(out_cfg)
        self._host = pg_cfg.get("host", "localhost")
        self._port = pg_cfg.get("port", 5432)
        self._database = pg_cfg.get("database", "")
        self._user = pg_cfg.get("username") or pg_cfg.get("user") or "postgres"
        self._password = pg_cfg.get("password", "")
        self._schema = pg_cfg.get("schema", "public")
        self._ssl = pg_cfg.get("ssl", False)
        self._pool_min = pg_cfg.get("pool_min", 2)
        self._pool_max = pg_cfg.get("pool_max", 10)
        self._sync_commit = pg_cfg.get("sync_commit", False)
        self._prepared_statements = pg_cfg.get("prepared_statements", True)

        self._pool: asyncpg.Pool | None = None
        self._pool_lock = asyncio.Lock()

        self._init_metrics()

    # ── Pool lifecycle ──────────────────────────────────────────────────

    async def _connect_pool(self) -> None:
        ssl_ctx = self._ssl
        if isinstance(self._ssl, bool) and self._ssl:
            import ssl as _ssl

            ssl_ctx = _ssl.create_default_context()
            ssl_ctx.check_hostname = False
            ssl_ctx.verify_mode = _ssl.CERT_NONE

        ic("_connect_pool", self._host, self._port, self._database)

        async def _init_conn(conn):
            if not self._sync_commit:
                await conn.execute("SET synchronous_commit = OFF")

        self._pool = await asyncpg.create_pool(
            host=self._host,
            port=self._port,
            database=self._database,
            user=self._user,
            password=self._password,
            min_size=self._pool_min,
            max_size=self._pool_max,
            ssl=ssl_ctx if self._ssl else None,
            init=_init_conn,
            statement_cache_size=100 if self._prepared_statements else 0,
        )
        log_event(
            logger,
            "info",
            "OUTPUT",
            "PostgreSQL pool created",
            host=self._host,
            port=self._port,
            operation="CONNECT",
            sync_commit=self._sync_commit,
            prepared_statements=self._prepared_statements,
        )

    async def _close_pool(self) -> None:
        ic("_close_pool", self._host, self._port)
        pool, self._pool = self._pool, None
        if pool:
            await pool.close()
            log_event(
                logger,
                "info",
                "OUTPUT",
                "PostgreSQL pool closed",
                host=self._host,
                port=self._port,
                operation="DISCONNECT",
            )

    # ── SQL execution ───────────────────────────────────────────────────

    async def _execute_ops(self, ops: list) -> None:
        pool = self._pool
        if pool is None:
            raise ConnectionError("PostgreSQL pool is not connected")
        grouped = group_insert_ops(ops)
        ic("_execute_ops", len(ops), "grouped", len(grouped))
        async with pool.acquire() as conn:
            async with conn.transaction():
                for op in grouped:
                    if isinstance(op, _MultiRowInsert):
                        sql, params = self._multi_row_insert_sql(op)
                        log_event(
                            logger,
                            "debug",
                            "OUTPUT",
                            "SQL exec (multi-row INSERT, %d rows)" % len(op.rows),
                            operation="INSERT",
                        )
                        await conn.execute(sql, *params)
                    else:
                        sql, params = op.to_sql()
                        doc_id = getattr(op, "doc_id", None)
                        log_event(
                            logger,
                            "debug",
                            "OUTPUT",
                            "SQL exec",
                            operation=getattr(op, "operation", None),
                            doc_id=doc_id,
                        )
                        await conn.execute(sql, *params)

    @staticmethod
    def _multi_row_insert_sql(mri: _MultiRowInsert) -> tuple[str, list]:
        """Build a single INSERT … VALUES (…),(…),… for asyncpg $N placeholders."""
        col_list = ", ".join(f'"{c}"' for c in mri.columns)
        params: list = []
        value_groups: list[str] = []
        idx = 1
        for row in mri.rows:
            placeholders = ", ".join(f"${idx + i}" for i in range(len(row)))
            value_groups.append(f"({placeholders})")
            params.extend(row)
            idx += len(row)
        sql = f'INSERT INTO "{mri.table}" ({col_list}) VALUES {", ".join(value_groups)}'
        return sql, params

    # ── Error classification ────────────────────────────────────────────

    def _is_transient(self, exc: Exception) -> bool:
        if asyncpg is None:
            return False
        if isinstance(
            exc,
            (
                asyncpg.InterfaceError,
                asyncpg.ConnectionDoesNotExistError,
                ConnectionError,
                OSError,
                TimeoutError,
            ),
        ):
            return True
        if isinstance(exc, asyncpg.PostgresError):
            return getattr(exc, "sqlstate", None) in _TRANSIENT_SQLSTATES
        return False

    def _error_class(self, exc: Exception) -> str:
        if asyncpg is None:
            return "unknown"
        if isinstance(
            exc,
            (
                asyncpg.InterfaceError,
                asyncpg.ConnectionDoesNotExistError,
                ConnectionError,
                OSError,
            ),
        ):
            return "connection"
        if isinstance(exc, TimeoutError):
            return "timeout"
        if isinstance(exc, asyncpg.PostgresError):
            state = getattr(exc, "sqlstate", "") or ""
            if state.startswith("23"):
                return "constraint_violation"
            if state in ("40001", "40P01"):
                return "deadlock"
            if state.startswith("08") or state.startswith("57"):
                return "connection"
            if state.startswith("53"):
                return "resource_exhaustion"
            if state == "55P03":
                return "lock_contention"
            if state == "42P01":
                return "table_not_found"
            if state == "42501":
                return "permission_denied"
            if state.startswith("42"):
                return "syntax_or_schema"
            if state.startswith("22"):
                return "data_type"
            if state.startswith("28"):
                return "auth_failure"
            if state == "3D000":
                return "invalid_database"
            if state == "3F000":
                return "invalid_schema"
            return f"pg_{state}" if state else "unknown_pg"
        return "unknown"

    # ── Health check ────────────────────────────────────────────────────

    async def _test_connection(self) -> None:
        pool = self._pool
        if pool is None:
            raise ConnectionError("PostgreSQL pool is not connected")
        async with pool.acquire() as conn:
            await conn.fetchval("SELECT 1")
        ic("_test_connection: OK", self._host, self._port)
        log_event(
            logger,
            "info",
            "OUTPUT",
            "PostgreSQL reachable",
            host=self._host,
            port=self._port,
        )


# ── Introspection (standalone functions, not part of the forwarder) ──────


async def introspect_tables(pg_cfg: dict) -> list[dict]:
    """
    Connect to PostgreSQL and return all tables with their columns.

    Returns: [
        {
            "table_name": "orders",
            "schema": "public",
            "columns": [
                {"name": "id", "type": "integer", "nullable": false, "default": "nextval(...)"},
                {"name": "status", "type": "character varying", "nullable": true, "default": null},
                ...
            ],
            "primary_key": ["id"],
            "foreign_keys": [
                {"column": "customer_id", "references_table": "customers", "references_column": "id"}
            ]
        },
        ...
    ]
    """
    if asyncpg is None:
        raise RuntimeError("asyncpg library not installed – pip install asyncpg")

    ssl_ctx = None
    if pg_cfg.get("ssl"):
        import ssl as _ssl

        ssl_ctx = _ssl.create_default_context()
        ssl_ctx.check_hostname = False
        ssl_ctx.verify_mode = _ssl.CERT_NONE

    conn = await asyncpg.connect(
        host=pg_cfg.get("host", "localhost"),
        port=pg_cfg.get("port", 5432),
        database=pg_cfg.get("database", ""),
        user=pg_cfg.get("user", "postgres"),
        password=pg_cfg.get("password", ""),
        ssl=ssl_ctx,
    )

    try:
        schema = pg_cfg.get("schema", "public")

        # Get all tables
        tables_rows = await conn.fetch(
            """
            SELECT table_name
            FROM information_schema.tables
            WHERE table_schema = $1 AND table_type = 'BASE TABLE'
            ORDER BY table_name
        """,
            schema,
        )

        result = []
        for trow in tables_rows:
            table_name = trow["table_name"]

            # Get columns
            col_rows = await conn.fetch(
                """
                SELECT column_name, data_type, udt_name, is_nullable,
                       column_default, character_maximum_length,
                       numeric_precision, numeric_scale
                FROM information_schema.columns
                WHERE table_schema = $1 AND table_name = $2
                ORDER BY ordinal_position
            """,
                schema,
                table_name,
            )

            columns = []
            for c in col_rows:
                col_type = c["data_type"]
                if col_type == "USER-DEFINED":
                    col_type = c["udt_name"]
                display_type = col_type
                if c["character_maximum_length"]:
                    display_type += f"({c['character_maximum_length']})"
                elif c["numeric_precision"] and col_type in ("numeric", "decimal"):
                    display_type += (
                        f"({c['numeric_precision']},{c['numeric_scale'] or 0})"
                    )

                columns.append(
                    {
                        "name": c["column_name"],
                        "type": col_type,
                        "display_type": display_type,
                        "nullable": c["is_nullable"] == "YES",
                        "default": c["column_default"],
                    }
                )

            # Get primary key columns
            pk_rows = await conn.fetch(
                """
                SELECT kcu.column_name
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                    ON tc.constraint_name = kcu.constraint_name
                    AND tc.table_schema = kcu.table_schema
                WHERE tc.table_schema = $1 AND tc.table_name = $2
                    AND tc.constraint_type = 'PRIMARY KEY'
                ORDER BY kcu.ordinal_position
            """,
                schema,
                table_name,
            )
            pk_cols = [r["column_name"] for r in pk_rows]

            # Get foreign keys
            fk_rows = await conn.fetch(
                """
                SELECT kcu.column_name,
                       ccu.table_name AS references_table,
                       ccu.column_name AS references_column
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                    ON tc.constraint_name = kcu.constraint_name
                    AND tc.table_schema = kcu.table_schema
                JOIN information_schema.constraint_column_usage ccu
                    ON tc.constraint_name = ccu.constraint_name
                    AND tc.table_schema = ccu.table_schema
                WHERE tc.table_schema = $1 AND tc.table_name = $2
                    AND tc.constraint_type = 'FOREIGN KEY'
            """,
                schema,
                table_name,
            )
            fks = [
                {
                    "column": r["column_name"],
                    "references_table": r["references_table"],
                    "references_column": r["references_column"],
                }
                for r in fk_rows
            ]

            result.append(
                {
                    "table_name": table_name,
                    "schema": schema,
                    "columns": columns,
                    "primary_key": pk_cols,
                    "foreign_keys": fks,
                }
            )

        return result
    finally:
        await conn.close()


async def introspect_single_table(pg_cfg: dict, table_name: str) -> dict | None:
    """Introspect a single table. Returns the table dict or None."""
    tables = await introspect_tables(pg_cfg)
    for t in tables:
        if t["table_name"] == table_name:
            return t
    return None
